#!/usr/bin/env bash
set -euo pipefail

ORACLE_CONTAINER_NAME="${ORACLE_CONTAINER_NAME:-file-stat-oracle}"

docker exec "${ORACLE_CONTAINER_NAME}" mkdir -p /opt/oracle/oradata/recovery_area

docker exec -i "${ORACLE_CONTAINER_NAME}" sqlplus -s / as sysdba <<'SQL'
WHENEVER SQLERROR EXIT SQL.SQLCODE;

ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE = 10G SCOPE=BOTH;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST = '/opt/oracle/oradata/recovery_area' SCOPE=SPFILE;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ALTER PLUGGABLE DATABASE ALL OPEN;

ARCHIVE LOG LIST;
EXIT;
SQL
