WHENEVER SQLERROR CONTINUE;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

CREATE USER C##DBZUSER IDENTIFIED BY dbz CONTAINER = ALL;

GRANT CREATE SESSION TO C##DBZUSER CONTAINER = ALL;
GRANT SET CONTAINER TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ON V_$DATABASE TO C##DBZUSER CONTAINER = ALL;
GRANT FLASHBACK ANY TABLE TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ANY TABLE TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT_CATALOG_ROLE TO C##DBZUSER CONTAINER = ALL;
GRANT EXECUTE_CATALOG_ROLE TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ANY TRANSACTION TO C##DBZUSER CONTAINER = ALL;
GRANT LOGMINING TO C##DBZUSER CONTAINER = ALL;
GRANT CREATE TABLE TO C##DBZUSER CONTAINER = ALL;
GRANT LOCK ANY TABLE TO C##DBZUSER CONTAINER = ALL;
GRANT CREATE SEQUENCE TO C##DBZUSER CONTAINER = ALL;

ALTER USER C##DBZUSER QUOTA UNLIMITED ON USERS CONTAINER = ALL;

GRANT EXECUTE ON DBMS_LOGMNR TO C##DBZUSER CONTAINER = ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ON V_$LOG TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ON V_$LOG_HISTORY TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ON V_$LOGFILE TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ON V_$TRANSACTION TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ON V_$MYSTAT TO C##DBZUSER CONTAINER = ALL;
GRANT SELECT ON V_$STATNAME TO C##DBZUSER CONTAINER = ALL;
